language: python
cache: pip
branches:
  only:
    - source
python:
  - 3.10
install:
  - gem install sass
  - pip install -r requirements.txt
  - cp readme.md output\README.md
  - git config --global user.email "chapagain.aaditya@gmail.com"
  - git config --global user.name "Aaditya Chapagain"
  - git clone https://github.com/aadityachapagain/Flex.git themes/Flex
  - git clone https://github.com/getpelican/pelican-plugins

script:
  - fab publish:"Build site"