name = "aadityachapagain"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat_populate_process_env"]

[build]
command = "npm run pages:build"

[site]
bucket = ".vercel/output/static"

[observability]
enabled = true