[package]
name = "api-worker"
version = "0.1.0"
edition = "2021"
authors = [ "aaditya chapagain <aadityachapagain101@gmail.com>" ]

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version="0.5.0", features=['http', 'axum'] }
worker-macros = { version="0.5.0", features=['http'] }
axum  = { version = "0.7", default-features = false, features = ["json"] }
tower-service = "0.3.2"
console_error_panic_hook = { version = "0.1.1" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
chrono = { version = "0.4.41", features = ["wasmbind"] }
tower-http = { version = "0.6.2", features = ["cors"] }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
futures = "0.3.31"
